name: Archive Old Pocket Items

on:
  schedule:
    - cron: '0 12 * * 5'  # Run at 12:00 (noon) UTC every Friday

jobs:
  archive-items:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Archive old Pocket items
        env:
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
        run: python archive_old_pocket_items.py
