name: RSS to Pocket

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  

jobs:
  update-pocket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run RSS to Pocket script
        env:
          POCKET_ACCESS_TOKEN: ${{ secrets.POCKET_ACCESS_TOKEN }}
          POCKET_CONSUMER_KEY: ${{ secrets.POCKET_CONSUMER_KEY }}
        run: python rss_to_pocket.py
      - name: Commit and push changes
        env:
          MY_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_TOKEN_FOR_POCKET_RSS }}  
        run: |
          git config --global user.email "upgundecha@gmail.com"
          git config --global user.name "Unmesh Gundecha"
          git add .
          git commit -m "Automated commit message" -a || echo "No changes to commit"
          git push https://${{ env.MY_PERSONAL_ACCESS_TOKEN }}@github.com/upgundecha/pocket-rss-sync.git HEAD:main
